export const blogArticles = [
  {
    id: 'career-model-canvas',
    title: 'Career Model Canvas',
    categories: ['career'],
    date: 'June 16, 2026',
    dateISO: '2026-06-16',
    readTime: 8,
    image: '/images/career-model-canvas.png',
    imageAlt: 'Team collaborating around a career planning canvas on a desk',
    imagePosition: 'center center',
  },
  {
    id: 'consciously-design-your-future',
    title: 'Consciously Design Your Future',
    categories: ['career'],
    date: 'November 9, 2024',
    dateISO: '2024-11-09',
    readTime: 7,
    image: '/images/consciously-design-your-future.png',
    imageAlt: 'Create your future text on a bright yellow background',
    imagePosition: 'center center',
  },
  {
    id: 'vision-board',
    title: 'Vision Board: Your Gateway to Manifesting Dreams into Reality',
    categories: ['career'],
    date: 'December 20, 2024',
    dateISO: '2024-12-20',
    readTime: 6,
    image: '/images/vision-board.png',
    imageAlt: 'Person pinning images onto a vision board on a corkboard',
    imagePosition: '55% center',
  },
  {
    id: 'self-appreciation',
    title: 'Self-Appreciation: A Simple Way to Improve Your Confidence',
    categories: ['career', 'wellbeing'],
    date: 'February 28, 2025',
    dateISO: '2025-02-28',
    readTime: 5,
    image: '/images/self-appreciation.png',
    imageAlt: 'Person standing on a mountain overlook with arms raised in celebration',
    imagePosition: 'center 40%',
  },
  {
    id: 'who-cares',
    title: 'Who cares? The freedom begins when you stop overthinking what others think.',
    categories: ['career', 'wellbeing'],
    date: 'March 20, 2026',
    dateISO: '2026-03-20',
    readTime: 4,
    image: '/images/who-cares.png',
    imageAlt: 'Person at a desk reflecting thoughtfully',
    imagePosition: '65% center',
  },
  {
    id: 'stop-asking-how-are-you',
    title: 'STOP asking How Are You?',
    categories: ['leadership'],
    date: 'May 6, 2026',
    dateISO: '2026-05-06',
    readTime: 6,
    image: '/images/stop-asking-how-are-you.png',
    imageAlt: 'Red stop sign with the word STOP in white letters',
    imagePosition: 'center center',
  },
  {
    id: 'constructive-feedback',
    title: 'Mastering the Art of Constructive Feedback in the Workplace',
    categories: ['leadership'],
    date: 'September 11, 2024',
    dateISO: '2024-09-11',
    readTime: 7,
    image: '/images/constructive-feedback.png',
    imageAlt: 'Colleagues clapping and smiling during a workplace meeting',
    imagePosition: 'center 40%',
  },
  {
    id: 'breaking-the-bias',
    title: 'Breaking the Bias: A Personal Journey of Awareness and Growth',
    categories: ['leadership', 'wellbeing'],
    date: 'March 23, 2025',
    dateISO: '2025-03-23',
    readTime: 6,
    image: '/images/breaking-the-bias.png',
    imageAlt: 'Person walking along a forest path on a personal journey',
    imagePosition: 'center center',
  },
  {
    id: 'breaking-through-procrastination',
    title: 'Breaking Through Procrastination: Unlock Your Productivity Potential',
    categories: ['productivity'],
    date: 'November 8, 2025',
    dateISO: '2025-11-08',
    readTime: 10,
    image: '/images/hero.png',
  },
  {
    id: 'amazing-day',
    title: 'The amazing day: Structure your day for peak performance & productivity',
    categories: ['productivity'],
    date: 'May 6, 2025',
    dateISO: '2025-05-06',
    readTime: 8,
    image: '/images/amazing-day.png',
    imageAlt: 'Hands writing a to-do list in a planner on a wooden desk',
    imagePosition: 'center center',
  },
  {
    id: 'book-reading-habit',
    title: 'How to Build a Book Reading Habit: A Simple, Practical Approach to Sustainable Change',
    categories: ['productivity'],
    date: 'April 22, 2026',
    dateISO: '2026-04-22',
    readTime: 5,
    image: '/images/book-reading-habit.png',
    imageAlt: 'Person holding and reading an open book',
    imagePosition: 'center 45%',
  },
  {
    id: 'understanding-fears',
    title: 'Understanding and Managing Fears',
    categories: ['wellbeing'],
    date: 'October 10, 2024',
    dateISO: '2024-10-10',
    readTime: 8,
    image: '/images/understanding-fears.png',
    imageAlt: 'Wooden letter tiles spelling the word FEAR on a rustic wooden surface',
    imagePosition: 'center 55%',
  },
].map((article) => ({
  ...article,
  href: `/blog/${article.id}`,
  external: false,
}));

export const LEGACY_SLUGS = {
  'breaking-through-procrastination-unlock-your-productivity-potential': 'breaking-through-procrastination',
};

export function resolveArticleSlug(slug) {
  return LEGACY_SLUGS[slug] ?? slug;
}

export function getBlogArticleById(id) {
  return blogArticles.find((article) => article.id === id);
}
